# red = 0
---
start: Welcome in this wonderful irc-simulator !

end: irc-simulator is deconnected.

characters:
  - name: Pierre
    color: red #red, blue, green, white
    speed: 0.5
    status: 0 #0 < speed < 1

  - name: Paul
    color: green
    speed: 0.5
    status: 1

  - name: Jacques
    color: blue
    speed: 0.5
    status: 1

date:
  year: 2015
  month: 2 #March
  day: 0 #Sunday
  hour: local
  min: local
  sec: local
