# red = 0
---
start: "Welcome in this wonderful irc-simulator !"

end: "irc-simulator is deconnected."
end_wait: 10000

# MODEL FORMATING = '%' + parameters
# parameters :
# P -> the character name with color formating
# DATE PARAMETERS -> see all parameters on cplusplus website
# http://www.cplusplus.com/reference/iomanip/put_time/

model: "(%d/%m/%G - %H:%M:%S) %P dit :"

characters:
  - name: Pierre
    color: red #red, blue, green, white
    speed: 0.5
    status: 0 #0 < speed < 1

  - name: Paul
    color: green
    speed: 0.5
    status: 1

  - name: Jacques
    color: blue
    speed: 0.5
    status: 1

# DATE OPTIONS (TODO):
# 'local' -> formated with dialog.txt date node
# 'automatic' -> formated with previous date and end waiting time of previous dialog
# for each date you can put global time as exemple

date:
  year: 2048
  month: local
  day: local
  hour: local
  min: local
  sec: automatic
