# red = 0
---
start: ...

end: Jade est déconnectée.
# model: (%y/%d %h:%m:%s) %p :

characters:
  - name: Will
    color: red #red, blue, green, white
    speed: 0.5
    status: 0 #0 < speed < 1

  - name: Jade
    color: green
    speed: 0.2
    status: 1

date:
  year: 2015
  month: 2 #March
  day: 0 #Sunday
  hour: local
  min: local
  sec: local
